{% set version = "2020.6" %}

package:
  name: gromacs
  version: {{ version }}

build:
# switch to number 100 for mpi version
# 1: rebuild with plumed 2.8
  number: 1

source:
  url: http://ftp.gromacs.org/pub/gromacs/gromacs-{{ version }}.tar.gz
  sha256: d8bbe57ed3c9925a8cb99ecfe39e217f930bed47d5268a9e42b33da544bdb2ee

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - binutils
    - cmake
    - llvm-openmp  # [osx]
    - python
  host:
    - openmpi
    - fftw
    - libhwloc 1.*
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - plumed
  run:
    - openmpi
    - fftw
    - libhwloc 1.*
    - llvm-openmp  # [osx]
    - plumed >=2

test:
  commands:
    - gmx_mpi -version
    - gmx_mpi mdrun -h | grep plumed

about:
  home: http://www.gromacs.org/
  license: GNU Lesser General Public License (LGPL)
  summary: GROMACS is a versatile package to perform molecular dynamics.

